#!/bin/bash

DOMAIN=$1
PROBLEM=$2
TIMEOUT=$3

./cleanup

### CEA 
TIME=$(timeout $TIMEOUT ./plan $DOMAIN $PROBLEM --heuristic "hcea=cea(cost_type=2)" --search "lazy_greedy(hcea)" | grep "Total time:")

# postprocessing
if [ -e "sas_plan" ]; then
	sed -i '/\(verify_.* \)/d' sas_plan
	RESULT=$(./VAL/validate $DOMAIN $PROBLEM sas_plan)
	if [[ "$RESULT" == *"Plan valid"* ]]; then
		echo "$DOMAIN $PROBLEM cea valid $TIME"
	else
		echo "$DOMAIN $PROBLEM cea invalid $TIME"
	fi

	if [ "$3" == "1" ]; then
		echo $RESULT
	fi
fi
