#!/bin/bash

DIR=$(cd $(dirname "$0"); pwd)

if [ "$4" != "" ]; then
	LOG_FILE="$4"
else
	LOG_FILE="$DIR/cea.log"
fi

DOMAIN=$1
PROBLEM=$2
TIMEOUT=$3

if [ "$TIMEOUT" != "" ]; then
	TIMEOUT="timeout $TIMEOUT"
fi

$DIR/cleanup

### CEA 
command time -o running.time -f "%U" $TIMEOUT $DIR/plan $DOMAIN $PROBLEM --heuristic "hcea=cea(cost_type=2)" --search "lazy_greedy(hcea)" > $LOG_FILE

TIME=$(cat running.time)
rm -f running.time

# postprocessing
if [ -e "sas_plan" ]; then
	sed -i '/\(verify_.* \)/d' sas_plan
	RESULT=$($DIR/VAL/validate $DOMAIN $PROBLEM sas_plan)
	if [[ "$RESULT" == *"Plan valid"* ]]; then
		echo "$DOMAIN $PROBLEM cea valid $TIME"
	else
		echo "$DOMAIN $PROBLEM cea invalid $TIME"
	fi

	if [ "$3" == "1" ]; then
		echo $RESULT
	fi
fi
