#!/bin/bash

DIR=$(cd $(dirname "$0"); pwd)

DOMAIN=$1
PROBLEM=$2
TIMEOUT=$3

if [ "$TIMEOUT" != "" ]; then
	TIMEOUT="timeout $TIMEOUT"
fi

$DIR/cleanup

### CG
TIME=$($TIMEOUT $DIR/plan $DOMAIN $PROBLEM --heuristic "hcg=cg(cost_type=1)" --search "lazy_greedy(hcg)" | grep "Total time:")

# postprocessing
if [ -e "sas_plan" ]; then
	sed -i '/\(verify_.* \)/d' sas_plan
	RESULT=$($DIR/VAL/validate $DOMAIN $PROBLEM sas_plan)
	if [[ "$RESULT" == *"Plan valid"* ]]; then
		echo "$DOMAIN $PROBLEM cg() valid $TIME"
	else
		echo "$DOMAIN $PROBLEM cg() invalid $TIME"
	fi

	if [ "$3" == "1" ]; then
		echo $RESULT
	fi
fi
