#!/bin/bash

DOMAIN=$1
PROBLEM=$2
TIMEOUT=$3

./cleanup

### FF 
TIME=$(timeout $TIMEOUT ./plan $DOMAIN $PROBLEM --heuristic "hff=ff(cost_type=0)" --search "lazy_greedy(hff)" | grep "Total time:")

# postprocessing
if [ -e "sas_plan" ]; then
	sed -i '/\(verify_.* \)/d' sas_plan
	RESULT=$(./VAL/validate $DOMAIN $PROBLEM sas_plan)
	if [[ "$RESULT" == *"Plan valid"* ]]; then
		echo "$DOMAIN $PROBLEM ff valid $TIME"
	else
		echo "$DOMAIN $PROBLEM ff invalid $TIME"
	fi

	if [ "$3" == "1" ]; then
		echo $RESULT
	fi
fi
