#!/bin/bash

DOMAIN=$1
PROBLEM=$2
TIMEOUT=$3

./cleanup

### LAMA-FF
TIME=$(timeout $TIMEOUT ./plan $DOMAIN $PROBLEM \
	--heuristic "hlm,hff=lm_ff_syn(lm_rhw(reasonable_orders=true,lm_cost_type=2,cost_type=2), admissible=false, optimal=false, cost_type=2)" \
	--search "lazy_greedy([hff,hlm],preferred=[hff,hlm])" | grep "Total time:")

# postprocessing
if [ -e "sas_plan" ]; then
	sed -i '/\(verify_.* \)/d' sas_plan
	RESULT=$(./VAL/validate $DOMAIN $PROBLEM sas_plan)
	if [[ "$RESULT" == *"Plan valid"* ]]; then
		echo "$DOMAIN $PROBLEM lama_syn valid $TIME"
	else
		echo "$DOMAIN $PROBLEM lama_syn invalid $TIME"
	fi

	if [ "$3" == "1" ]; then
		echo $RESULT
	fi
fi
