#!/bin/bash

#DOMAIN="benchmark/cloudburst.pddl"
#PROBLEM="benchmark/cb-p02.pddl"

DOMAIN="benchmark/rovers/domain.pddl"
PROBLEM="benchmark/rovers/p03.pddl"

#DOMAIN=benchmark/service.pddl
#PROBLEM=benchmark/s06.pddl

if [ -e "sas_plan" ]; then
	rm sas_plan
fi

#./plan $DOMAIN $PROBLEM --heuristic "hlm,hff=lm_ff_syn(lm_rhw(reasonable_orders=true,lm_cost_type=2,cost_type=2))" --search "lazy_greedy([hff,hlm],preferred=[hff,hlm])"
./plan $DOMAIN $PROBLEM --heuristic "hlm,hff=lm_ff_syn(lm_rhw(reasonable_orders=true,lm_cost_type=2), admissible=false, optimal=false, cost_type=0)" --search "lazy_greedy([hff,hlm],preferred=[hff,hlm])"

# postprocessing
if [ -e "sas_plan" ]; then
	sed -i '/\(verify_.* \)/d' sas_plan
	cat sas_plan
   echo ""
   ./VAL/validate $DOMAIN $PROBLEM sas_plan
   #./VAL/validate -v $DOMAIN $PROBLEM sas_plan
fi
