#! /bin/bash

set -e

BASEDIR="$(dirname "$0")"

function die {
    echo "$@" 1>&2
    exit 1
}

function usage {
    die "usage: $(basename "$0") [DOMAIN_FILE] PROBLEM_FILE SEARCH_OPTION ..."
}

# Paths to planner components
TRANSLATE="$BASEDIR/translate/translate.py"
PREPROCESS="$BASEDIR/preprocess/preprocess"
SEARCH="$BASEDIR/search/downward"

# Need to explicitly ask for GNU time (from MacPorts) on Mac OS X.
if [[ "$(uname)" == "Darwin" ]]; then
    TIME="gtime"
    if ! which $TIME >/dev/null; then
        die "$TIME must be installed on Mac OSX (from MacPorts, perhaps) for this to work"
    fi
else
    TIME="command time"
fi

TIME="$TIME --output=elapsed.time --format=%S\n%U\n"

if [[ "$#" < 2 ]]; then
    usage
fi

echo "1. Running translator"
if [[ -e "$2" ]]; then
    echo "Second argument is a file name: use two translator arguments."
    $TIME "$TRANSLATE" "$1" "$2"
    shift 2
else
    echo "Second argument is not a file name: auto-detect domain file."
    $TIME "$TRANSLATE" "$1"
    shift
fi
echo

echo "2. Running preprocessor"
$TIME --append "$PREPROCESS" < output.sas
echo

echo "3. Running search"
if [[ "$1" == "cg" ]]; then
	"$SEARCH" < output --search "lazy_greedy(cg(cost_type=2))"
elif [[ "$1" == "ff" ]]; then
	"$SEARCH" < output --search "lazy_greedy(ff(cost_type=0))"
elif [[ "$1" == "cea" ]]; then
	"$SEARCH" < output --search "lazy_greedy(cea(cost_type=2))"
elif [[ "$1" == "mad" ]]; then
	"$SEARCH" < output --heuristic "hmad=mad()" --search "lazy_greedy(hmad,preferred=hmad)"
elif [[ "$1" == "lama" ]]; then
	"$SEARCH" < output \
	--heuristic "hlm,hff=lm_ff_syn(lm_rhw(reasonable_orders=true,lm_cost_type=2,cost_type=0), admissible=false, optimal=false, cost_type=0)" \
	--search "lazy_greedy([hff,hlm],preferred=[hff,hlm])"
else
	"$SEARCH" < output "$@"
fi
echo
