#!/bin/bash

DEBUG=0
DOMAIN=benchmark/service.pddl
PROBLEMS[1]="benchmark/s01.pddl"
PROBLEMS[2]="benchmark/s02.pddl"
PROBLEMS[3]="benchmark/s03.pddl"
PROBLEMS[4]="benchmark/s04.pddl"
PROBLEMS[5]="benchmark/s05.pddl"
PROBLEMS[6]="benchmark/s06.pddl"
PROBLEMS[7]="benchmark/s07.pddl"
PROBLEMS[8]="benchmark/s08.pddl"
PROBLEMS[9]="benchmark/s09.pddl"
PROBLEMS[10]="benchmark/s10.pddl"
PROBLEMS[11]="benchmark/s11.pddl"
PROBLEMS[12]="benchmark/s12.pddl"
PROBLEMS[13]="benchmark/s13.pddl"
PROBLEMS[14]="benchmark/s14.pddl"
PROBLEMS[15]="benchmark/s15.pddl"
PROBLEMS[16]="benchmark/s16.pddl"

if [ -e "all_plans" ]; then
	rm all_plans
fi

for PROBLEM in "${PROBLEMS[@]}"
do
	./cleanup

	if [ $DEBUG == 1 ]; then
		### Landmark
		./plan $DOMAIN $PROBLEM --landmarks "lm=lm_rhw(conjunctive_landmarks=true, disjunctive_landmarks=true)" --heuristic "hlm=lmcount(lm, admissible=false, optimal=false, pref=false)" --search "lazy_greedy(hlm, preferred=hlm)"
	else
		./plan $DOMAIN $PROBLEM --landmarks "lm=lm_rhw(conjunctive_landmarks=true, disjunctive_landmarks=true)" --heuristic "hlm=lmcount(lm, admissible=false, optimal=false, pref=false)" --search "lazy_greedy(hlm, preferred=hlm)" 1>/dev/null 2>/dev/null
	fi	

	echo -n "$PROBLEM..."
	# postprocessing
	echo $PROBLEM >> all_plans
	if [ -e "sas_plan" ]; then
		sed -i '/\(verify_.* \)/d' sas_plan
		RESULT=$(./VAL/validate $DOMAIN $PROBLEM sas_plan)

		cat sas_plan >> all_plans
   	echo "" >> all_plans
		echo "$RESULT" >> all_plans

		VALID="Plan valid"
		if [[ "$RESULT" == *"$VALID"* ]]; then
			echo "valid"
		else
			echo "not-valid"
		fi

	else
		echo "no-solution" >> all_plans
		echo "no-solution"
	fi

	echo "=====" >> all_plans

done

if [ $DEBUG == 1 ]; then
	cat all_plans
fi

rm all_plans
